apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mgmt-svc
spec:
  ports:
    - name: rabbitmq-mgmt
      protocol: TCP
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
